빠른 시작: false
스케쥴러 디버그: false
게임 시작 시 순위 공개: true
게임 시작 시 인벤토리 초기화: true
경험치 바 사용: true
순위 교체 시 순위 교체 공개: true
게임 시작 시 돌검 지급: true
순위 공개 타이머: 30
패널티 시간: 10
탈락 시간: 120
아레나 모드 1위 탈락: false
아레나 모드 활성화 시간: -1
아레나 모드 활성화 인원: 3
아레나 모드 탈락 시간: 15